/**
 * API providing data for binat test-client-application
 * API providing data for binat test-client-application. In this version, validation and required fields of the schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tomerk@kkl.org.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * an object type of a Contact\'s customer
 */
export interface Contacts { 
    /**
     * unique id of the Contacts
     */
    id?: number;
    /**
     * Contact name or description
     */
    fullName?: string | null;
    /**
     * Office Number
     */
    officeNumber?: string | null;
    /**
     * Email Address
     */
    email?: string | null;
    /**
     * unique id of the Customer
     */
    CustomerId?: number;
    /**
     * Fax number
     */
    fax?: string | null;
    /**
     * mobile number
     */
    mobile?: string | null;
    /**
     * Passport Number
     */
    PassportNumber?: string | null;
    /**
     * Passport Number
     */
    IdNumber?: string | null;
}

