/**
 * API providing data for binat test-client-application
 * API providing data for binat test-client-application. In this version, validation and required fields of the schemas.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: tomerk@kkl.org.il
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * an object type of Customers
 */
export interface Customers { 
    /**
     * unique id of the Customers
     */
    id?: number | null;
    /**
     * Customers name or description
     */
    name?: string | null;
    /**
     * unique id of the Customers
     */
    customerNumber?: number | null;
    /**
     * City name or description
     */
    city?: string | null;
    /**
     * City name or description
     */
    street?: string | null;
    postalCode?: number | null;
}

